Add PHP sample and reorganize sections
okteto/samples pull request #75
Opened 2019-12-20 02:23 UTC by pchico83

2019-12-21 10:28 UTC, rlamana approved these changes

2020-01-04 20:00 UTC, rberrelleza commented on README.md
>  This repository contains examples of how to develop applications directly in your Kubernetes cluster using [okteto](https://github.com/okteto/okteto), with different platforms and deployment technolo
```suggestion
This repository contains examples of how to develop applications directly in your Kubernetes cluster using [okteto](https://github.com/okteto/okteto), with different programming languages, frameworks and deployment tool.
```

2020-01-04 20:00 UTC, rberrelleza commented on README.md
> +## By languages
```suggestion
## Programming Languages
```

2020-01-04 20:01 UTC, rberrelleza commented on README.md
> +## By frameworks
```suggestion
## Frameworks
```

2020-01-04 20:01 UTC, rberrelleza commented on README.md
> +## By deployment tools
```suggestion
## Deployment Tools
```

2020-01-04 20:01 UTC, rberrelleza commented on README.md
> +## Remote
```suggestion
## Remote IDEs
```

2020-01-04 20:03 UTC, rberrelleza commented on README.md
> +1. [OpenFaaS](https://medium.com/okteto/how-to-develop-a-serverless-app-with-openfaas-and-okteto-d85435f0eca1)
I'd put this on a 'Serverless' section. While not wrong, I don't think most people relate functions with a deployment tool but rather as a development model.

2020-01-04 20:04 UTC, rberrelleza requested changes
Not sure what problem we are trying to solve here, but if you like this order better go for it 👍

2020-01-04 20:20 UTC, merged